### ISSUE TITLE
sqlite3 module isn't built correctly under armhf

### ISSUE THREAD

**Issue by amyspark** [linuxserver/docker-thelounge#25]
Hey all.

I'm testing your Docker image on a Raspberry Pi 3 B+ with Raspbian (`armhf` architecture). Logs show that your image doesn't have a working `sqlite3` module.

```
pi@Merida:~/Desktop/merida $ docker-compose up
Creating thelounge
Attaching to thelounge
thelounge    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
thelounge    | [s6-init] ensuring user provided files have correct perms...exited 0.
thelounge    | [fix-attrs.d] applying ownership & permissions fixes...
thelounge    | [fix-attrs.d] done.
thelounge    | [cont-init.d] executing container initialization scripts...
thelounge    | [cont-init.d] 10-adduser: executing...
thelounge    |
thelounge    | -------------------------------------
thelounge    |           _         ()
thelounge    |          | |  ___   _    __
thelounge    |          | | / __| | |  /  \
thelounge    |          | | \__ \ | | | () |
thelounge    |          |_| |___/ |_|  \__/
thelounge    |
thelounge    |
thelounge    | Brought to you by linuxserver.io
thelounge    | We gratefully accept donations at:
thelounge    | https://www.linuxserver.io/donate/
thelounge    | -------------------------------------
thelounge    | GID/UID
thelounge    | -------------------------------------
thelounge    |
thelounge    | User uid:    1000
thelounge    | User gid:    1000
thelounge    | -------------------------------------
thelounge    |
thelounge    | [cont-init.d] 10-adduser: exited 0.
thelounge    | [cont-init.d] 30-config: executing...
thelounge    | [cont-init.d] 30-config: exited 0.
thelounge    | [cont-init.d] 99-custom-scripts: executing...
thelounge    | [custom-init] no custom scripts found exiting...
thelounge    | [cont-init.d] 99-custom-scripts: exited 0.
thelounge    | [cont-init.d] done.
thelounge    | [services.d] starting services
thelounge    | [services.d] done.
thelounge    | 2019-05-15 16:52:37 [INFO] Configuration file created at /config/config.js.
thelounge    | 2019-05-15 16:52:37 [ERROR] Unable to load sqlite3 module. You might need to install it manually.
thelounge    | 2019-05-15 16:52:39 [INFO] The Lounge v3.0.1 (Node.js 10.14.2 on linux arm)
thelounge    | 2019-05-15 16:52:39 [INFO] Configuration file: /config/config.js
thelounge    | 2019-05-15 16:52:39 [INFO] Available at http://:::9000/ in public mode
thelounge    | 2019-05-15 16:52:39 [INFO] New VAPID key pair has been generated for use with push subscription.
^CGracefully stopping... (press Ctrl+C again to force)
Stopping thelounge ... done
```

This is my `uname -a`: `Linux Merida 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

And my `docker-compose.yml` (running on a random folder at my desktop):

```yaml
version: '2'
services:
        thelounge:
                image: linuxserver/thelounge:latest
                container_name: thelounge
                environment:
                       - PUID=1000
                       - PGID=1000
                volumes:
                        - ./thelounge:/var/opt/thelounge
                ports:
                        - 9000:9000
                restart: unless-stopped
```
